In [2]:
import matplotlib.pyplot as plt
import pickle
import numpy as np

In [3]:
data = open('data/UHTelPCC.pkl', 'rb')

In [4]:
data = pickle.load(data, encoding='latin-1')

In [5]:
(train_x,train_y), (val_x,val_y), (test_x,test_y) = data

In [6]:
train_y

array([  1,   1,   1, ..., 507, 507, 507], dtype=uint16)

In [7]:
req_labels = [1, 2, 5, 6,8, 9, 11, 38, 98, 140, 151, 162, 173, 184, 195, 204, 218, 229, 240, 262, 284, 306, 320,
404, 426, 441]

In [9]:
n_train_x, n_train_y = list(), list()
n_val_x, n_val_y = list(), list()
n_test_x, n_test_y = list(), list()

for val, label in zip(train_x, train_y):
    if label in req_labels:
        n_train_x += [val]
        n_train_y += [label]
        
for val, label in zip(val_x, val_y):
    if label in req_labels:
        n_val_x += [val]
        n_val_y += [label]
        
for val, label in zip(test_x, test_y):
    if label in req_labels:
        n_test_x += [val]
        n_test_y += [label]

num = [len(set(n_train_y)) == len(req_labels), len(set(n_val_y)) == len(req_labels), 
       len(set(n_test_y)) == len(req_labels)]
n_train_x = np.array(n_train_x)
n_train_y = np.array(n_train_y)
n_val_x = np.array(n_val_x)
n_val_y = np.array(n_val_y)
n_test_x = np.array(n_test_x)
n_test_y = np.array(n_test_y)

print(n_train_x.shape, n_val_x.shape, n_test_x.shape, num)

(11581, 1024) (2283, 1024) (2283, 1024) [True, True, True]


In [10]:
dump = [(n_train_x,n_train_y), (n_val_x,n_val_y), (n_test_x,n_test_y)]
f = open('data/chars.pkl', 'wb')
pickle.dump(dump, f)
f.close()

In [11]:
f = open('data/chars.pkl', 'rb')
n_data = pickle.load(f)

In [12]:
(train_x,train_y), (val_x,val_y), (test_x,test_y) = n_data

In [14]:
if (val_x == test_x).all():
    print(Yes)

In [21]:
count = np.array([np.count_nonzero(train_y == x) for x in req_labels])
count.max(), count.min()

(1716, 8)

In [22]:
count

array([ 563,  175,  117,    8,  338,   70,  109, 1143,  296,  315,  169,
        747,  386, 1716, 1148,  257,  411,  573, 1115,  932,  436,  225,
        253,   19,   28,   32])

In [24]:
count_val = np.array([np.count_nonzero(val_y == x) for x in req_labels])
count_test = np.array([np.count_nonzero(test_y == x) for x in req_labels])

In [25]:
count_val

array([120,  37,  25,   1,  72,  15,  23, 213,  63,  67,  35, 159,  82,
       305, 214,  54,  87, 122, 207, 174,  93,  48,  53,   3,   5,   6])

In [26]:
count_test

array([120,  37,  25,   1,  72,  15,  23, 213,  63,  67,  35, 159,  82,
       305, 214,  54,  87, 122, 207, 174,  93,  48,  53,   3,   5,   6])

In [27]:
count_val == count_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])