In [32]:
import matplotlib.pyplot as plt
import pickle
import numpy as np

In [33]:
data = open('data/UHTelPCC.pkl', 'rb')

In [34]:
data = pickle.load(data, encoding='latin-1')

In [35]:
(train_x,train_y), (val_x,val_y), (test_x,test_y) = data

In [36]:
train_y

array([  1,   1,   1, ..., 507, 507, 507], dtype=uint16)

In [37]:
req_labels = [1, 2, 5, 6,8, 9, 11, 38, 98, 140, 151, 162, 173, 184, 195, 204, 218, 229, 240, 262, 284, 306, 320,
404, 426, 441]

In [38]:
train_x = train_x[np.equal(train_y, req_labels)]
train_y = train_y[np.equal(train_y, req_labels)]

val_x = val_x[np.equal(train_y, req_labels)]
val_y = val_y[np.equal(train_y, req_labels)]

test_x = test_x[np.equal(train_y, req_labels)]
test_y = test_y[np.equal(train_y, req_labels)]

print(train_x.shape, val_x.shape, test_x.shape)

ValueError: operands could not be broadcast together with shapes (50000,) (26,) 

In [49]:
a = [1, 2, 3, 4, 5, 6, 7]
b = [2, 3, 4]
a = a[a == b]
a = []
a = a + [1]
a
a += a; a

[1, 1]

In [52]:
n_train_x, n_train_y = list(), list()
n_val_x, n_val_y = list(), list()
n_test_x, n_test_y = list(), list()

for val, label in zip(train_x, train_y):
    if label in req_labels:
        n_train_x += [val]
        n_train_y += [label]
        
for val, label in zip(val_x, val_y):
    if label in req_labels:
        n_val_x += [val]
        n_val_y += [label]
        
for val, label in zip(test_x, test_y):
    if label in req_labels:
        n_test_x += [val]
        n_test_y += [label]

num = [len(set(n_train_y)) == len(req_labels), len(set(n_val_y)) == len(req_labels), 
       len(set(n_test_y)) == len(req_labels)]
n_train_x = np.array(n_train_x)
n_train_y = np.array(n_train_y)
n_val_x = np.array(n_val_x)
n_val_y = np.array(n_val_y)
n_test_x = np.array(n_test_x)
n_test_y = np.array(n_test_y)

print(n_train_x.shape, n_val_x.shape, n_test_x.shape, num)

(11581, 1024) (2283, 1024) (2283, 1024) [True, True, True]


In [53]:
dump = [(n_train_x,n_train_y), (n_val_x,n_val_y), (n_test_x,n_test_y)]
f = open('data/chars.pkl', 'wb')
pickle.dump(dump, f)
f.close()

In [54]:
f = open('data/chars.pkl', 'rb')
n_data = pickle.load(f)

[(array([[255, 255,   0, ..., 255, 255, 255],
         [255, 255,   0, ..., 255, 255, 255],
         [255, 255,   0, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint16),
  array([  1,   1,   1, ..., 441, 441, 441], dtype=uint16)),
 (array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255,   0, ..., 255, 255, 255],
         [255, 255,   0, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255]], dtype=uint16),
  array([  1,   1,   1, ..., 441, 441, 441], dtype=uint16)),
 (array([[255, 255, 255, ..., 255, 255, 255],
         [255, 255,   0, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         ...,
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 255, ..., 255, 255, 255],
         [255, 255, 25

In [59]:
(train_x,train_y), (val_x,val_y), (test_x,test_y) = n_data

In [62]:
(val_x == test_x)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True, False, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])